version: "3.8"

services:
  led-controller:
    build: .
    container_name: led-controller
    ports:
      - "3000:3000"  # Frontend
      - "8000:8000"  # Backend API
    restart: unless-stopped
    volumes:
      - ./config.json:/app/config.json:ro
    environment:
      - NODE_ENV=production
      - PYTHONUNBUFFERED=1
